/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SubscriptionManager {
  export type SubscriptionIntentStruct = {
    subscriber: AddressLike;
    merchant: AddressLike;
    amount: BigNumberish;
    interval: BigNumberish;
    startTime: BigNumberish;
    maxPayments: BigNumberish;
    maxTotalAmount: BigNumberish;
    expiry: BigNumberish;
    nonce: BigNumberish;
  };

  export type SubscriptionIntentStructOutput = [
    subscriber: string,
    merchant: string,
    amount: bigint,
    interval: bigint,
    startTime: bigint,
    maxPayments: bigint,
    maxTotalAmount: bigint,
    expiry: bigint,
    nonce: bigint
  ] & {
    subscriber: string;
    merchant: string;
    amount: bigint;
    interval: bigint;
    startTime: bigint;
    maxPayments: bigint;
    maxTotalAmount: bigint;
    expiry: bigint;
    nonce: bigint;
  };
}

export interface SubscriptionManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PROTOCOL_FEE_BPS"
      | "PYUSD_ADDRESS"
      | "SUBSCRIPTION_INTENT_TYPEHASH"
      | "createSubscription"
      | "executedPayments"
      | "subscriptions"
      | "verifyIntent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PaymentExecuted"
      | "PaymentFailed"
      | "SubscriptionCancelled"
      | "SubscriptionCreated"
      | "SubscriptionPaused"
      | "SubscriptionResumed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PROTOCOL_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PYUSD_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUBSCRIPTION_INTENT_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createSubscription",
    values: [SubscriptionManager.SubscriptionIntentStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executedPayments",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyIntent",
    values: [SubscriptionManager.SubscriptionIntentStruct, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "PROTOCOL_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PYUSD_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUBSCRIPTION_INTENT_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executedPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyIntent",
    data: BytesLike
  ): Result;
}

export namespace PaymentExecutedEvent {
  export type InputTuple = [
    subscriptionId: BytesLike,
    subscriber: AddressLike,
    merchant: AddressLike,
    amount: BigNumberish,
    paymentNumber: BigNumberish
  ];
  export type OutputTuple = [
    subscriptionId: string,
    subscriber: string,
    merchant: string,
    amount: bigint,
    paymentNumber: bigint
  ];
  export interface OutputObject {
    subscriptionId: string;
    subscriber: string;
    merchant: string;
    amount: bigint;
    paymentNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentFailedEvent {
  export type InputTuple = [
    subscriptionId: BytesLike,
    subscriber: AddressLike,
    merchant: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    subscriptionId: string,
    subscriber: string,
    merchant: string,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    subscriptionId: string;
    subscriber: string;
    merchant: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCancelledEvent {
  export type InputTuple = [
    subscriptionId: BytesLike,
    subscriber: AddressLike,
    merchant: AddressLike
  ];
  export type OutputTuple = [
    subscriptionId: string,
    subscriber: string,
    merchant: string
  ];
  export interface OutputObject {
    subscriptionId: string;
    subscriber: string;
    merchant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCreatedEvent {
  export type InputTuple = [
    subscriptionId: BytesLike,
    subscriber: AddressLike,
    merchant: AddressLike,
    amount: BigNumberish,
    interval: BigNumberish,
    maxPayments: BigNumberish,
    maxTotalAmount: BigNumberish,
    expiry: BigNumberish
  ];
  export type OutputTuple = [
    subscriptionId: string,
    subscriber: string,
    merchant: string,
    amount: bigint,
    interval: bigint,
    maxPayments: bigint,
    maxTotalAmount: bigint,
    expiry: bigint
  ];
  export interface OutputObject {
    subscriptionId: string;
    subscriber: string;
    merchant: string;
    amount: bigint;
    interval: bigint;
    maxPayments: bigint;
    maxTotalAmount: bigint;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionPausedEvent {
  export type InputTuple = [subscriptionId: BytesLike, subscriber: AddressLike];
  export type OutputTuple = [subscriptionId: string, subscriber: string];
  export interface OutputObject {
    subscriptionId: string;
    subscriber: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionResumedEvent {
  export type InputTuple = [subscriptionId: BytesLike, subscriber: AddressLike];
  export type OutputTuple = [subscriptionId: string, subscriber: string];
  export interface OutputObject {
    subscriptionId: string;
    subscriber: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SubscriptionManager extends BaseContract {
  connect(runner?: ContractRunner | null): SubscriptionManager;
  waitForDeployment(): Promise<this>;

  interface: SubscriptionManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PROTOCOL_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  PYUSD_ADDRESS: TypedContractMethod<[], [string], "view">;

  SUBSCRIPTION_INTENT_TYPEHASH: TypedContractMethod<[], [string], "view">;

  createSubscription: TypedContractMethod<
    [
      intent: SubscriptionManager.SubscriptionIntentStruct,
      signature: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  executedPayments: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  subscriptions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        subscriber: string;
        merchant: string;
        amount: bigint;
        interval: bigint;
        startTime: bigint;
        maxPayments: bigint;
        maxTotalAmount: bigint;
        expiry: bigint;
        nonce: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  verifyIntent: TypedContractMethod<
    [
      intent: SubscriptionManager.SubscriptionIntentStruct,
      signature: BytesLike
    ],
    [[boolean, string] & { valid: boolean; signer: string }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PROTOCOL_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PYUSD_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SUBSCRIPTION_INTENT_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createSubscription"
  ): TypedContractMethod<
    [
      intent: SubscriptionManager.SubscriptionIntentStruct,
      signature: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executedPayments"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "subscriptions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        subscriber: string;
        merchant: string;
        amount: bigint;
        interval: bigint;
        startTime: bigint;
        maxPayments: bigint;
        maxTotalAmount: bigint;
        expiry: bigint;
        nonce: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyIntent"
  ): TypedContractMethod<
    [
      intent: SubscriptionManager.SubscriptionIntentStruct,
      signature: BytesLike
    ],
    [[boolean, string] & { valid: boolean; signer: string }],
    "view"
  >;

  getEvent(
    key: "PaymentExecuted"
  ): TypedContractEvent<
    PaymentExecutedEvent.InputTuple,
    PaymentExecutedEvent.OutputTuple,
    PaymentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentFailed"
  ): TypedContractEvent<
    PaymentFailedEvent.InputTuple,
    PaymentFailedEvent.OutputTuple,
    PaymentFailedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCancelled"
  ): TypedContractEvent<
    SubscriptionCancelledEvent.InputTuple,
    SubscriptionCancelledEvent.OutputTuple,
    SubscriptionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCreated"
  ): TypedContractEvent<
    SubscriptionCreatedEvent.InputTuple,
    SubscriptionCreatedEvent.OutputTuple,
    SubscriptionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionPaused"
  ): TypedContractEvent<
    SubscriptionPausedEvent.InputTuple,
    SubscriptionPausedEvent.OutputTuple,
    SubscriptionPausedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionResumed"
  ): TypedContractEvent<
    SubscriptionResumedEvent.InputTuple,
    SubscriptionResumedEvent.OutputTuple,
    SubscriptionResumedEvent.OutputObject
  >;

  filters: {
    "PaymentExecuted(bytes32,address,address,uint256,uint256)": TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;
    PaymentExecuted: TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;

    "PaymentFailed(bytes32,address,address,uint256,string)": TypedContractEvent<
      PaymentFailedEvent.InputTuple,
      PaymentFailedEvent.OutputTuple,
      PaymentFailedEvent.OutputObject
    >;
    PaymentFailed: TypedContractEvent<
      PaymentFailedEvent.InputTuple,
      PaymentFailedEvent.OutputTuple,
      PaymentFailedEvent.OutputObject
    >;

    "SubscriptionCancelled(bytes32,address,address)": TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;
    SubscriptionCancelled: TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;

    "SubscriptionCreated(bytes32,address,address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;
    SubscriptionCreated: TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;

    "SubscriptionPaused(bytes32,address)": TypedContractEvent<
      SubscriptionPausedEvent.InputTuple,
      SubscriptionPausedEvent.OutputTuple,
      SubscriptionPausedEvent.OutputObject
    >;
    SubscriptionPaused: TypedContractEvent<
      SubscriptionPausedEvent.InputTuple,
      SubscriptionPausedEvent.OutputTuple,
      SubscriptionPausedEvent.OutputObject
    >;

    "SubscriptionResumed(bytes32,address)": TypedContractEvent<
      SubscriptionResumedEvent.InputTuple,
      SubscriptionResumedEvent.OutputTuple,
      SubscriptionResumedEvent.OutputObject
    >;
    SubscriptionResumed: TypedContractEvent<
      SubscriptionResumedEvent.InputTuple,
      SubscriptionResumedEvent.OutputTuple,
      SubscriptionResumedEvent.OutputObject
    >;
  };
}
