# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
contracts:
- name: RelayerRegistry
  handler: src/EventHandlers.ts
  events:
  - event: EmergencySlash(address indexed relayer, uint256 amount, string reason)
  - event: ExecutionRecorded(address indexed relayer, bool success, uint256 feeAmount)
  - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
  - event: RelayerRegistered(address indexed relayer, uint256 stakedAmount)
  - event: RelayerRestaked(address indexed relayer, uint256 amount, uint256 newStake)
  - event: RelayerSlashed(address indexed relayer, uint256 slashAmount, uint256 remainingStake)
  - event: RelayerUnregistered(address indexed relayer, uint256 returnedStake)
  - event: SlashingParametersUpdated(uint256 slashAmount, uint256 failureThreshold)
  - event: WithdrawalRequested(address indexed relayer, uint256 requestTime)
- name: SubscriptionManager
  handler: src/EventHandlers.ts
  events:
  - event: CrossChainPaymentInitiated(bytes32 indexed subscriptionId, address indexed subscriber, address subscriberToken, uint256 sourceChainId, uint256 targetChainId, uint256 amount)
  - event: NexusAttestationSubmitted(bytes32 indexed subscriptionId, uint256 indexed paymentNumber, string attestationId)
  - event: NexusAttestationVerified(string indexed attestationId)
  - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
  - event: PaymentExecuted(bytes32 indexed subscriptionId, address indexed subscriber, address indexed merchant, address token, uint256 paymentNumber, uint256 amount, uint256 fee, address relayer)
  - event: PaymentFailed(bytes32 indexed subscriptionId, address indexed subscriber, address indexed merchant, uint256 amount, string reason)
  - event: SubscriptionCancelled(bytes32 indexed subscriptionId, address indexed subscriber, address indexed merchant)
  - event: SubscriptionCreated(bytes32 indexed subscriptionId, address indexed subscriber, address indexed merchant, address token, uint256 amount, uint256 interval, uint256 maxPayments, uint256 maxTotalAmount, uint256 expiry)
  - event: SubscriptionPaused(bytes32 indexed subscriptionId, address indexed subscriber)
  - event: SubscriptionResumed(bytes32 indexed subscriptionId, address indexed subscriber)
  - event: TokenAdded(address indexed token)
  - event: TokenRemoved(address indexed token)
networks:
- id: 84532
  start_block: 0
  contracts:
  - name: RelayerRegistry
    address:
    - 0xD05DbfD9a66d9B388B513902c4F717B9C5E75Dd2
  - name: SubscriptionManager
    address:
    - 0x34b058f0870Bc58E1EE82a656985766738B5cD69
- id: 11155111
  start_block: 0
  contracts:
  - name: SubscriptionManager
    address:
    - 0xb351Ee33129F1e3d995FE546a747F67B55fA8A17
  - name: RelayerRegistry
    address:
    - 0x0aEE7395C351607954d193FC719C2648f597BD6c
unordered_multichain_mode: true
preload_handlers: true
